# Generated by Django 5.1.6 on 2025-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_measurement_image_alter_measurement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
