
services:
  app:
    build: . 
    container_name: fastapi_ads_app2
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy 
    restart: unless-stopped
    
  db:
    image: postgres:15-alpine 
    container_name: postgres_ads_db2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "127.0.0.1:5434:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    restart: unless-stopped 

volumes:
  postgres_data:
    driver: local 